version: "3"
services:
    grafana:
      #build:
      image: grafana/grafana:5.1.0
      container_name: grafana
      environment: 
        - GF_SERVER_ROOT_URL=http://localhost:30000
        - GF_SECURITY_ADMIN_PASSWORD=123456
      #volumes:
      #   - grafana-storage:/var/lib/grafana
      ports:
        - 30000:3000
      user: "104"
    mysql:
      image: mysql:5.7
      ports:
        - "30060:3306"
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: fiapdb
        MYSQL_USER: fiap
        MYSQL_PASSWORD: 123456
        